name: ideological_resonance_thesis
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.19
  - numpy=2.2.6
  - pandas=2.3.3
  - scipy=1.15.2
  - scikit-learn=1.7.2
  - matplotlib=3.10.8
  - plotly=6.6.0
  - gensim=4.4.0
  - emoji=2.15.0
  - ipykernel=7.1.0
  - ipython=8.37.0
  - jupyter_client=8.8.0
  - jupyter_core=5.9.1
  - openpyxl=3.1.5
  - pillow=12.1.0
  - pyside6=6.10.1
  - pip=26.0
